### ISSUE TITLE
Plugin does not work with webpack4

### ISSUE THREAD

**Issue by burnedram** [xipasduarte/no-emit-webpack-plugin#2]
I suspect webpack4 changed the type of `compilation.entrypoints` to be a proper Map, not just any object. This means that `Object.keys(compliation.entrypoints)` returns an empty list.

I will create a pull request that checks if it is a Map, and then use `Map.keys()` instead.

**Comment by xipasduarte** [comment]
From what I could find I believe you're right. They changed from Object to Map and Set. Will look at the PR and push a new release as soon as possible. Thanks.
